
        tstamptouse = tstamp_appended;
        marray = mcmc_get_walkers({tstamptouse}, {1:ri.nIter}, projdir);
        mcmc_plot(marray([1 2 4], :,:), mai.estNames([1 2 4]),...
            'savematlabfig', false, 'savejpeg', true,...
            'projdir', projdir, 'tstamp', tstamptouse);
        
        titls = {};
        lgds = {};
        mvarray = masterVecArray(marray, mai);
        marrayOrd = mvarray(mi(1).paramMaps(mi(1).orderingIx),:,:);
        mcmc_trajectories(mi(1).emo, di(mi(2).dataToMapTo), mi(1), marrayOrd,...
            titls, lgds,...
            'SimMode', 'meanstd', 'savematlabfig', false, 'savejpeg', true,...
            'projdir', projdir, 'tstamp', tstamptouse);
        
        marrayOrd = mvarray(mi(2).paramMaps(mi(2).orderingIx),:,:);
        titls = {};
        mcmc_trajectories(mi(2).emo, di(mi(2).dataToMapTo), mi(2), marrayOrd,...
            titls, lgds,...
            'SimMode', 'meanstd', 'savematlabfig', false, 'savejpeg', true,...
            'projdir', projdir, 'tstamp', tstamptouse);
        
        