%% Data info struct example


% Human readable description of the data. Should be specified using
% the format that makes it printable with the function fprintf.
% This is general information about the data and the circuit 
% you want to specify. For example, you can describe the experiment, 
% where the raw data is stored, who did the experiment. Use 
% the newline character to go to a new line. 
% 
dataInfo = ['Test data. \n'...
'Youngha test case. \n '...
'This is line three. '];

% time vector
tv = (0:360:7200)';


% units of the time vector. Allowed options are:
% 'seconds', 'minutes', 'hours', 'days', 'weeks'.
timeUnits = 'seconds'; 

% An array contianing the raw data that is generated by simulating
% the data according to the mcmc_info struct. Typically has dimensions
% corresponding to timepoints x measured outputs x replicates x doses.
da = rand(length(tv), 1, 3, 16);

% A 1 x number of measured species cell array of the strings
% specifying which species are dosed.
measuredNames = {'deGFP', 'RFP'}

 % A 1 x number measured species cell array of units corresponding to
% the raw data in the dataArray.
dataUnits = {'nM', 'nM'};

% a 1 by length(size(data_info.dataArray)) cell array of
% labels for the dimensions of the dataArray.
dimensionLabels = {'time points', 'measured species',...
        'replicates', 'doses'}''

% A 1 x number of dosed species cell array of the strings specifying
% which species are dosed.
dosedNames = {'GFP DNA'; 'RFP DNA'}

% A matrix of dose values of size
% # of dosed species by # of dose combinations
% In this case it is 2 species by 16 dose combinations
dosedVals = [1 1 1 1 5 5 5 5 20 20 20 20 80 80 80 80;
		     1 5 20 80 1 5 20 80 1 5 20 80 1 5 20 80 ]

doseUnits = {'nM', 'nM'}

di = struct('dataInfo', {dataInfo}, ...
        'timeVector', {tv}, ...
        'timeUnits', {timeUnits},...
        'dataArray', {da},...
        'measuredNames', {measuredNames},...
        'dataUnits', {dataUnits},...
        'dimensionLabels', {dimensionLabels}, ...
        'dosedNames', {dosedNames},...
        'dosedVals', {dosedVals}, ...
        'doseUnits', {doseUnits});